FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["newrelic-admin", "run-program", "gunicorn", "--bind", "0.0.0.0:8080", "application:application"]